Support for running from RAM, refactoring of the initramfs and cleanup support.
Finally, Subito GNU/Linux-libre is able to boot; the X server works great!

  - The initramfs was re-organized. Redundant directories were removed.
  - The initramfs init script now calls /bin/busybox directly. Only this file is
    installed from the BusyBox package.
  - Support for copying the root file system to RAM was added, through the
    "copy" boot code. This is similar to the Puppy Linux "pfix=ram" and the Slax
    "toram".
    Under live sessions, this feature can be used to copy the root file system
    image to the tmpfs layer, so the root partition can be unmounted. This is
    very useful for:
      - Optical media, which can be ejected to free the drive.
      - Slow USB drivers.
      - Diskless machines.
  - A new operation mode was added to roar-ng, "cleanup". This removed stuff
    left by "build".

Other, unrelated changes:
  - The kernel headers package now takes advantage of minor version patches.
  - Usage instructions were added to the README.
  - Added few missing packages and some BusyBox replacements.

diff --git a/roar-ng b/roar-ng
--- a/roar-ng
+++ b/roar-ng
@@ -9,7 +9,7 @@ CONFIGURATION_INSTALL_PATH="etc/roar-ng.conf"
 
 # determine where roar-ng runs from - if the configuration file exists in its
 # normal location, roar-ng is installed
-if [ -f "/$CONFIGURATION_INSTALL_PATH" ]
+if [ -f "/$CONFIGURATION_INSTALL_PATH" ] && [ ! -f roar-ng.conf ]
 then
 	INSTALL_PREFIX="/usr/share/roar-ng"
 	VAR_PREFIX="/var/roar-ng"
@@ -37,7 +37,7 @@ fi
 #############
 
 # the usage message
-USAGE="Usage: roar-ng {check|setup|download|extract}
+USAGE="Usage: roar-ng {check|setup|download|extract|cleanup}
        roar-ng build TYPE DEST
        roar-ng package [NAME]
 
@@ -52,13 +52,6 @@ DEFAULT_DISTRO="subito"
 DEFAULT_DISTRO_VERSION="2"
 DEFAULT_DISTRO_ARCH="x86_64"
 
-##################
-# package choice #
-##################
-
-# must-have packages for the initramfs
-INITRAMFS_PACKAGES="busybox"
-
 #########
 # paths #
 #########
@@ -68,6 +61,9 @@ PACKAGE_DB_FILE_NAME="packages.txt"
 
 # the package templates hacks script file name
 PACKAGE_TEMPLATE_HACKS_FILE_NAME="hacks.sh"
+
+# the BusyBox executable path
+BUSYBOX_PATH="$VAR_PREFIX/rootfs/usr/bin/busybox"
 
 # the kernel image path
 KERNEL_IMAGE_PATH="boot/vmlinuz"
@@ -868,6 +864,10 @@ _build_module() {
 		[ 0 -ne $? ] && return 1
 	done
 
+	# remove .gitignore files
+	find "$2" -name .gitignore -type f -delete
+	[ 0 -ne $? ] && return 1
+
 	# if at least one post-installation script exists, run it
 	[ ! -f "$post_install" ] && return 0
 	execute_and_delete_script "$post_install"
@@ -879,8 +879,16 @@ _build_module() {
 # input  : the extracted initramfs contents directory and the destination path
 # output : -
 _build_initramfs() {
-	# copy the initramfs packages and skeleton
-	_build_module "initramfs" "$1" "$INITRAMFS_PACKAGES"
+	# copy the initramfs skeleton
+	_build_module "initramfs" "$1" ""
+	if [ 0 -ne $? ]
+	then
+		echo "Error: failed to build the initramfs."
+		return 1
+	fi
+
+	# add BusyBox to the initramfs
+	install -D -m 4755 "$BUSYBOX_PATH" "$1/bin/busybox"
 	if [ 0 -ne $? ]
 	then
 		echo "Error: failed to build the initramfs."
@@ -940,12 +948,6 @@ _build_rootfs() {
 		    -i "$1/etc/$i"
 	done
 
-	# move things under /var to /run
-	mv "$1/var/run"/* "$1/run"
-	[ 0 -ne $? ] && return 1
-	mv "$1/var/lock"/* "$1/run/lock"
-	[ 0 -ne $? ] && return 1
-
 	# populate /root with the home directory skeleton
 	cp -a "$1/etc/skel"/* "$1/root"
 	[ 0 -ne $? ] && return 1
@@ -983,14 +985,14 @@ build_bootable_media_image() {
 	mkdir "$VAR_PREFIX/media/boot"
 	[ 0 -ne $? ] && return 1
 
-	# build the initramfs
-	_build_initramfs "$VAR_PREFIX/initramfs" \
-	                 "$VAR_PREFIX/media/boot/$INITRAMFS_FILE_NAME"
-	[ 0 -ne $? ] && return 1
-
 	# build the root file system image
 	_build_rootfs "$VAR_PREFIX/rootfs" \
 	              "$VAR_PREFIX/media/boot/$ROOT_FS_FILE_NAME"
+	[ 0 -ne $? ] && return 1
+
+	# build the initramfs
+	_build_initramfs "$VAR_PREFIX/initramfs" \
+	                 "$VAR_PREFIX/media/boot/$INITRAMFS_FILE_NAME"
 	[ 0 -ne $? ] && return 1
 
 	# move the kernel image from the root file system to the media itself
@@ -1191,6 +1193,20 @@ roar_ng_main() {
 			else
 				exit 0
 			fi
+			;;
+
+		cleanup)
+			for i in initramfs rootfs media
+			do
+				[ -d "$VAR_PREFIX/$i" ] && rm -rf "$VAR_PREFIX/$i"
+				if [ 0 -ne $? ]
+				then
+					echo "Error: failed to remove $VAR_PREFIX/$i."
+					exit 1
+				fi
+			done
+
+			exit 0
 			;;
 
 		*)
